name: Generate pull-modules scripts
on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git Config
        run: |
          git config user.name "Github Action Bot"
          git config user.email "<>"

      - name: Generate and push if different
        run: ./tools/auto-gen-pull-modules.sh
